# -*- coding: utf-8 -*-
"""punto_fijo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GC3RDc-QPkm9CEku5TbM79CRXs0-EIWS
"""

def punto_fijo(g, x0, tol=0.0005, max_iter=100):
    """
    Método de iteración del punto fijo.
    :param g: Función g(x) para iterar.
    :param x0: Valor inicial.
    :param tol: Tolerancia para la convergencia.
    :param max_iter: Máximo número de iteraciones.
    :return: Aproximación de la raíz.
    """
    for i in range(max_iter):
        x1 = g(x0)
        if abs(x1 - x0) < tol:
            return x1, i  # Retorna la raíz y el número de iteraciones
        x0 = x1
    raise ValueError("El método no convergió.")

# Función g(x) reescrita correctamente
g = lambda x: (18*x + 15)**(1/3)

# Valor inicial
x0 = 2

# Ejecutamos el método
raiz, iteraciones = punto_fijo(g, x0)

print(f"Raíz aproximada: {raiz}")
print(f"Iteraciones: {iteraciones}")